### ISSUE TITLE
Risk of ID not being unique

### ISSUE THREAD

**Issue by neilmispelaar** [irm1005-itec1005-fall-2023/assignment-03-BogdanStanley#2]
The challenge with using the `.length` property to generate a unique ID is that users can delete Todos. And if they can delete Todos then the length goes back down and it's possible in some cases that ToDos will be created using the same ID. And that's bad. 

https://github.com/irm1005-itec1005-fall-2023/assignment-03-BogdanStanley/blob/40d87fe946782266cf59991a22ebd90725e3b7f8/script.js#L62

**Comment by BogdanStanley** [comment]
fixed it
